[package]
name = "oppai-bot"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2018"

[dependencies]
log = "0.4"
rand = "0.8"
strum = { version = "0.20", features = [ "derive" ] }
clap = { version = "2.33", optional = true }
num_cpus = { version = "1.13", optional = true }
crossbeam = "0.8"
oppai-field = { path = "../field" }
oppai-minimax = { path = "../minimax" }
oppai-uct = { path = "../uct" }
oppai-patterns = { path = "../patterns" }
oppai-ladders = { path = "../ladders" }

[features]
cli = [ "clap", "num_cpus" ]
