[package]
name = "oppai-zero"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2021"

[dependencies]
rand.workspace = true
rand_distr.workspace = true
ndarray.workspace = true
num-traits.workspace = true
either.workspace = true
itertools.workspace = true
log.workspace = true
oppai-field = { path = "../field" }
oppai-rotate = { path = "../rotate" }

[dev-dependencies]
rand_xoshiro.workspace = true
