[package]
name = "oppai-zero-sgf"
version = "0.1.0"
authors = ["Evgeny Kurnevsky <kurnevsky@gmail.com>"]
license = "AGPL-3.0+"
description = "Open Points Artificial Intelligence"
edition = "2024"

[dependencies]
sgf-parse.workspace = true
oppai-field = { path = "../field" }
oppai-sgf = { path = "../sgf" }
oppai-zero = { path = "../zero" }

[dev-dependencies]
rand.workspace = true
rand_xoshiro.workspace = true
env_logger.workspace = true
